version=v05_standardvars
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Apr19_nobase_defaultcorr_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix    --memory=10000M --latest_mc_correction  --skip_baseline_selection
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Apr19_nobase_defaultcorr_simplecbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --simple_combination --memory=10000M --latest_mc_correction  --skip_baseline_selection
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_defaultcorr_nocbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix  --memory=10000M --latest_mc_correction --skip_baseline 
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_defaultcorr_covcbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --cov_combination --memory=10000M --latest_mc_correction --skip_baseline 
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_defaultcorr_simplecbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --simple_combination --memory=10000M --latest_mc_correction --skip_baseline 
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_defaultcorr_bdtcbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --add_BDT_combination --memory=10000M --skip_baseline --latest_mc_correction

python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_withbaseline_defaultcorr_nocbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix  --memory=10000M --latest_mc_correction  
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_withbaseline_defaultcorr_covcbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --cov_combination --memory=10000M --latest_mc_correction  
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_withbaseline_defaultcorr_simplecbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --simple_combination --memory=10000M --latest_mc_correction  
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name May2_withbaseline_defaultcorr_bdtcbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --add_BDT_combination --memory=10000M  --latest_mc_correction

#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Apr19_nobase_defaultcorr_cbcomb_latest_mc_${version}_matrix --queue_flavour 01\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --cov_combination --memory=10000M --latest_mc_correction --skip_baseline_selection
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Apr16_defaultcorr_cbcomb_${version}_nocalib --queue_flavour 00\:30:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --default_correction --cov_combination  --memory=8000M --latest_mc_correction
