version=v05_standardvars_trimmed

##files to compare the resolutions in the simulation, for different combinations
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_nocbcomb_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py  --memory=16000M --skip_baseline 
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_covcbcomb_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py  --cov_combination --memory=16000M --skip_baseline  
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_fullcovcbcomb_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --fullcov_combination --memory=16000M --skip_baseline 

##files to compare the effect of the sagitta bias correction in data
#python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_nocbcomb_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py  --memory=16000M  #no mc correction, no data correction, baseline selection applied

##files to compare the data/mc agreement for different combinations
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_defaultcorr_nocbcomb_latest_mc_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix  --memory=16000M --latest_mc_correction
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_defaultcorr_covcbcomb_latest_mc_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --cov_combination --memory=16000M --latest_mc_correction  
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_defaultcorr_fullcovcbcomb_latest_mc_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --fullcov_combination --memory=16000M --latest_mc_correction  
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_defaultcorr_simplecbcomb_latest_mc_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --simple_combination --memory=16000M --latest_mc_correction  
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_defaultcorr_covcbcombpercent_latest_mc_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --cov_combination_percent --memory=16000M --latest_mc_correction
python Submission/prepare_submission.py --tree_name MuonMomentumCalibrationTree --n_jobs 300 --job_name Jun8_withbaseline_defaultcorr_fullcovcbcombpercent_latest_mc_${version}_matrix --queue_flavour 01:50:\00 --file_flavour ${version} --filling_script Macros\/filling_script.py --load_calibration default_matrix   --fullcov_combination_percent --memory=16000M --latest_mc_correction

